services:
  libsql-database:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
        - 8080:8080
        - 5001:5001
    environment:
        - SQLD_NODE=primary
    volumes:
        - ./data/libsql:/var/lib/sqld
    container_name: database
  libsql-client:
    container_name: db-ui
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dbclient
    ports:
      - 3001:3000
    depends_on:
      - libsql-database
  discord-bot:
    container_name: fia-docs-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile.bot
    env_file: ./.env
    environment: 
      - DATABASE_URL=http://database:8080
    depends_on:
     - libsql-database
    

