services:
  libsql-database:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
        - 8080:8080
        - 5001:5001
    environment:
        - SQLD_NODE=primary
    volumes:
        - ./data/libsql:/var/lib/sqld
    container_name: database
  libsql-client:
    container_name: db-ui
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dbclient
    ports:
      - 3001:3000
    depends_on:
      - libsql-database

