edition = "2021"
fn_params_layout = "Vertical"
fn_call_width = 80
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
