# Node 22 is current LTS
FROM node:22-alpine
WORKDIR /app
# Install Git
RUN apk add --no-cache git
RUN git clone https://github.com/outerbase/studio.git /app
RUN npm ci
RUN npm run build
CMD npm start
